### PR TITLE
Fix build job failure due to missing dependency

### PR DESCRIPTION
**Pull request by leandropineda**
# Changes

- Added required dependencies to fix build job (see [error logs](https://build.ros2.org/job/Fdev__ros_amr_interop__ubuntu_focal_amd64/2/consoleFull#console-section-27))
- Cleaned up unused packages on `package.xml`
- Fixed tests that were failing because they were using GMT timestamps

---

Build farm job passed when run locally. See [this wiki page](https://github.com/inorbit-ai/ros_amr_interop/wiki/Running-build-farm-job-locally) for more instructions

### CODE REVIEW

**Comment by leandropineda** [comment]
@adamantivm ready for review! Also CC'ing @miguelgarcia for awareness on the GMT fix and the instructions for running the prerelease job locally.

**Review by adamantivm — COMMENTED** [review]
Awesome stuff @leandropineda !

One suggestion: you're adding GREAT documentation to the PRs and I am sad to see them buried in the PRs.

How about maybe dumping at least a link to "useful info in MRs" in the Wiki perhaps, or copying the useful bits in wiki pages?
Just an idea

**Comment by adamantivm** [comment]
Also, I suggest merge squashing this

**Comment by leandropineda** [comment]
Actually, a few entries on the Wiki sound like the right thing to do. I'll also add the instructions for releasing a new version while doing the next release

**Pull request merged**
