### PR TITLE
Modifying repository folder structure

### PR DESCRIPTION
**Pull request by leandropineda**
# Changes

* Changed folder structure to allow other modules to coexist on the same repository.
* Added `CHANGELOG.rst` summarizing PR changes and previous changes as well.
* Fixed license, description and license on `setup.py` file.

# Test

```bash
$ colcon test --packages-select massrobotics_amr_sender

Starting >>> massrobotics_amr_sender
Finished <<< massrobotics_amr_sender [2.34s]          

Summary: 1 package finished [2.46s]
$ colcon test-result --verbose

Summary: 21 tests, 0 errors, 0 failures, 0 skipped
```

### CODE REVIEW

**Comment by leandropineda** [comment]
@miguelgarcia @adamantivm I'll change repo name after merging this PR.

WDYT about folder organization? The suffix `_py` seems to be a common practice e.g. https://github.com/ros2/geometry2/tree/ros2/tf2_ros_py

**Comment by adamantivm** [comment]
I really like all these changes. The only last doubt I have is about package name, doubting my own suggestion of `mrai_sender` and wondering if we shouldnt use `massrobotics_amr_sender` instead.

Other than that LGTM

**Comment by leandropineda** [comment]
Changed name to `massrobotics_amr_sender` @adamantivm

**Review by adamantivm — APPROVED** [review]
Looking great!

**Comment by adamantivm** [comment]
That was a fast rename @leandropineda !

**Comment by miguelgarcia** [comment]
Great job @leandropineda LGTM too :D

**Pull request merged**
